package com.yujiedu.orm.poc;

// Generated Jan 23, 2015 2:58:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import com.yujiedu.service.poc.IUserInfo;

/**
 * PocUsr generated by hbm2java
 */
@Entity
@Table(name = "POC_USR", uniqueConstraints = @UniqueConstraint(columnNames = "USER_ID"))
public class PocUser implements java.io.Serializable, IUserInfo {

	private String userUuid;
	private String userId;
	private String password;
	private Date lastLoginDate;
	private Date recCrtDt;
	private Date recUpdDt;
	private String orgId = "POC";

	public PocUser() {
	}

	public PocUser(String userId, String pwd) {
		this.userUuid = UUID.randomUUID().toString().replaceAll("-", "");
		this.userId = userId;
		this.password = pwd;
		this.recCrtDt = new Date();
		this.recUpdDt = new Date();
	}

	public PocUser(String userUuid, String userId, String pwd, Date recCrtDt, Date recUpdDt) {
		this.userUuid = userUuid;
		this.userId = userId;
		this.password = pwd;
		this.recCrtDt = recCrtDt;
		this.recUpdDt = recUpdDt;
	}

	@Column(name = "LAST_LOGIN_DT", length = 26)
	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	@Column(name = "REC_CRT_DT", nullable = false, length = 26)
	public Date getRecCrtDt() {
		return this.recCrtDt;
	}

	@Version
	@Column(name = "REC_UPD_DT", nullable = false, length = 26)
	public Date getRecUpdDt() {
		return this.recUpdDt;
	}

	@Column(name = "USER_ID", unique = true, nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	@Id
	@Column(name = "USER_UUID", unique = true, nullable = false, length = 32)
	public String getUserUuid() {
		return this.userUuid;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public void setPassword(String pwd) {
		this.password = pwd;
	}

	public void setRecCrtDt(Date recCrtDt) {
		this.recCrtDt = recCrtDt;
	}

	public void setRecUpdDt(Date recUpdDt) {
		this.recUpdDt = recUpdDt;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public void setUserUuid(String userUuid) {
		this.userUuid = userUuid;
	}

	@Column(name = "ORG_UUID", length = 32)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Override
	@Transient
	public String getEmail() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	@Transient
	public String getStatus() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	@Transient
	public String getMobile() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	@Transient
	public String getUserName() {
		return userId;
	}

	@Override
	@Column(name = "PWD", nullable = false, length = 20)
	public String getPassword() {
		return password;
	}

	@Override
	public void setEmail(String email) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setStatus(String status) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setMobile(String mobile) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setUserName(String userName) {
		// TODO Auto-generated method stub

	}
}
