package com.yujiedu.orm.poc;
// Generated Jan 22, 2015 4:57:48 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


/**
 * PocEmp generated by hbm2java
 */
@Entity
@Table(name = "POC_EMP", uniqueConstraints = @UniqueConstraint(columnNames = "EMP_NO"))
public class PocEmp implements java.io.Serializable {

	private String empUuid;
	private PocDep pocDep;
	private String empNo;
	private String firstName;
	private String lastName;
	private Date recCrtDt;
	private Date recUpdDt;
	private String orgId;

	public PocEmp() {
	}

	public PocEmp(String empUuid, PocDep pocDep, String empNo, String firstName, String lastName, Date recCrtDt,
			Date recUpdDt) {
		this.empUuid = empUuid;
		this.pocDep = pocDep;
		this.empNo = empNo;
		this.firstName = firstName;
		this.lastName = lastName;
		this.recCrtDt = recCrtDt;
		this.recUpdDt = recUpdDt;
	}

	public PocEmp(String empUuid, String empNo, String firstName, String lastName, Date recCrtDt, Date recUpdDt) {
		this.empUuid = empUuid;
		this.empNo = empNo;
		this.firstName = firstName;
		this.lastName = lastName;
		this.recCrtDt = recCrtDt;
		this.recUpdDt = recUpdDt;
	}

	@Column(name = "EMP_NO", unique = true, nullable = false, length = 10)
	public String getEmpNo() {
		return this.empNo;
	}

	@Id
	@Column(name = "EMP_UUID", unique = true, nullable = false, length = 32)
	public String getEmpUuid() {
		return this.empUuid;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEP_UUID")
	public PocDep getPocDep() {
		return this.pocDep;
	}

	@Column(name = "REC_CRT_DT", nullable = false, length = 26)
	public Date getRecCrtDt() {
		return this.recCrtDt;
	}

	@Version
	@Column(name = "REC_UPD_DT", nullable = false, length = 26)
	public Date getRecUpdDt() {
		return this.recUpdDt;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public void setEmpUuid(String empUuid) {
		this.empUuid = empUuid;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setPocDep(PocDep pocDep) {
		this.pocDep = pocDep;
	}

	public void setRecCrtDt(Date recCrtDt) {
		this.recCrtDt = recCrtDt;
	}

	public void setRecUpdDt(Date recUpdDt) {
		this.recUpdDt = recUpdDt;
	}

	@Column(name = "ORG_UUID", length = 32)
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
}
